var current='home', operational='inventory', openTasks=4, language='हिंदी';
var nav=[['home','⌂','घर'],['tasks','✓','काम'],['farmers','♙','किसान'],['operations','▣','कामकाज'],['more','•••','और']];
var farmers=[['राम सिंह','गेहूं · 25 क्विंटल','आज 10:00 AM'],['मंजू देवी','धान · 18 क्विंटल','कल बैच बना'],['रानी कुमारी','सरसों · 9 क्विंटल','ओवरड्यू कलेक्शन'],['श्याम लाल','मक्का · 12 क्विंटल','ऑर्डर approved']];
function e(s){return s}
function renderNav(){document.getElementById('nav').innerHTML=nav.map(function(n){return '<button class="nav '+(current===n[0]?'active':'')+'" onclick="go(\''+n[0]+'\')"><b>'+n[1]+'</b>'+n[2]+'</button>'}).join('')}
function home(){return '<div class="hero"><div class="eyebrow">आज का काम</div><h1>'+openTasks+' काम बाकी हैं</h1><p>पहले प्राथमिकता 1 वाली फसल लें</p><button class="primary" onclick="go(\'tasks\')">आज के काम देखें  →</button></div><div class="metrics"><div class="metric card"><strong>1,250 <small>kg</small></strong><small>आज की कलेक्शन</small><div class="good">12% बेहतर</div></div><div class="metric card"><strong>4.6 <small>/ 5</small></strong><small>आपकी रेटिंग</small><div class="good">बहुत अच्छा</div></div></div><div class="section-kicker">तुरंत काम</div><h2 class="section-title">आपके शॉर्टकट</h2><div class="shortcuts"><button class="shortcut card" onclick="go(\'tasks\')"><div class="shortcut-icon">✓</div><strong>टास्क</strong><span>'+openTasks+' बाकी</span></button><button class="shortcut card" onclick="go(\'farmers\')"><div class="shortcut-icon">♙</div><strong>किसान</strong><span>42 जुड़े हैं</span></button><button class="shortcut card" onclick="go(\'operations\');setOperation(\'batch\')"><div class="shortcut-icon">▣</div><strong>बैच बनाएं</strong><span>कलेक्शन के बाद</span></button><button class="shortcut card" onclick="go(\'operations\');setOperation(\'dispatch\')"><div class="shortcut-icon">⇢</div><strong>डिस्पैच</strong><span>1 तैयार</span></button></div><div class="section-kicker">बोलकर काम करें</div><h2 class="section-title">AI आवाज़ सहायक</h2><button class="voice" onclick="listen()"><div class="voice-orb">◉</div><div><strong id="voiceTitle">बोलिए, मैं काम कर दूँगा</strong><span>टास्क, किसान, ऑर्डर या अपडेट पूछें</span></div></button><div class="section-kicker" style="margin-top:24px">फील्ड अपडेट</div><h2 class="section-title">आज की स्थिति</h2><div class="status-list card"><div class="status-row"><div class="status-icon">✓</div><div><strong>2 कलेक्शन पूरे हुए</strong><span>राम सिंह और मंजू देवी के बैच बने</span></div><b class="tag">सफल</b></div><div class="status-row"><div class="status-icon" style="background:#fff2da;color:#8b6210">!</div><div><strong>1 काम को ध्यान चाहिए</strong><span>रानी कुमारी का कलेक्शन ओवरड्यू है</span></div><button class="tag warn" onclick="go(\'tasks\')">अभी देखें</button></div><div class="status-row"><div class="status-icon">↻</div><div><strong>सभी रिकॉर्ड सुरक्षित और सिंक हैं</strong><span>ऑफलाइन रिकॉर्डिंग भी उपलब्ध है</span></div><b class="tag">सिंक</b></div></div>'}
function tasks(){var rows=[['1','रानी कुमारी','सरसों · 9 क्विंटल','Bansgaon, Ward 4','ओवरड्यू'],['2','राम सिंह','गेहूं · 25 क्विंटल','Lakhimpur, Sector 2','आज 2:00 PM'],['3','मंजू देवी','धान · 18 क्विंटल','Kheri, Village Road','आज 5:00 PM'],['4','श्याम लाल','मक्का · 12 क्विंटल','Gola, Block 7','कल 10:00 AM']];return '<div class="screen-head"><div><h1>दैनिक कार्य</h1><p>पहले सबसे जरूरी कलेक्शन पूरा करें</p></div><button class="pill" onclick="showToast(\'Priority-wise list active है\')">Priority 1–4</button></div><div class="notice">⏰ रानी कुमारी का कलेक्शन ओवरड्यू है। कृपया आज ही visit करें।</div>'+rows.map(function(r,i){return '<article class="task card"><div class="priority">'+r[0]+'</div><div style="flex:1"><h3>'+r[1]+'</h3><p>'+r[2]+' · '+r[3]+'</p><div class="task-meta"><span class="micro">☎ 98765 43210</span><span class="micro">'+r[4]+'</span></div></div><button onclick="completeTask(this,'+i+')">'+(i===0?'शुरू करें':'देखें')+'</button></article>'}).join('')}
function farmersView(){return '<div class="screen-head"><div><h1>मेरे किसान</h1><p>42 assigned farmers · 4 villages</p></div><button class="pill" onclick="showToast(\'किसान सूची अपडेट हो गई\')">Filter</button></div><div class="map"><strong>असाइन्ड क्षेत्र · लखनऊ</strong><small>Sector 1, 2, 4, 7, 9 · गांव और किसान markers</small><span class="pin one"><i>1</i></span><span class="pin two"><i>2</i></span></div><input class="search" placeholder="किसान या गांव खोजें" oninput="filterFarmers(this.value)"><div id="farmerList">'+farmerRows(farmers)+'</div>'}
function farmerRows(items){return items.map(function(f){return '<button class="farmer card"><div class="avatar">'+f[0].slice(0,1)+'</div><div style="flex:1"><strong>'+f[0]+'</strong><span>'+f[1]+' · '+f[2]+'</span></div><b class="tag">देखें</b></button>'}).join('')}
function operations(){return '<div class="screen-head"><div><h1>कामकाज</h1><p>इन्वेंटरी, ऑर्डर और डिस्पैच</p></div></div><div class="operation-tabs">'+[['inventory','इन्वेंटरी'],['orders','ऑर्डर'],['dispatch','डिस्पैच'],['batch','बैच']].map(function(t){return '<button class="'+(operational===t[0]?'active':'')+'" onclick="setOperation(\''+t[0]+'\')">'+t[1]+'</button>'}).join('')+'</div><div id="operationBody">'+operationBody()+'</div>'}
function operationBody(){if(operational==='inventory')return '<article class="feature-card card"><h3>Agri Park Cold Storage</h3><p>Sector 9, Agri Park, Lucknow, UP · मैनेजर: सीमा सिंह · 98765 41111</p><div class="inline-grid"><div class="info"><small>Cold storage</small><b>24 MT / 50 MT</b></div><div class="info"><small>तापमान</small><b>4°C</b></div><div class="info"><small>गेहूं A Grade</small><b>23 MT</b></div><div class="info"><small>धान A Grade</small><b>18 MT</b></div></div></article><button class="row-action" onclick="showToast(\'Inventory stock details खुले\')"><div class="shortcut-icon">▦</div><div><strong>इन्वेंटरी स्टॉक देखें</strong><span>आपके क्षेत्र की फसल, grade और quantity</span></div><b class="arrow">›</b></button>';
if(operational==='orders')return '<article class="feature-card card"><h3>ORD12345 · किसान का ऑर्डर</h3><p>1250 kg गेहूं · किसान को status दिखाई दे रहा है</p><div class="timeline"><div class="step"><i>✓</i><div><strong>Checked</strong><span>10 May · 10:00 AM</span></div></div><div class="step"><i>✓</i><div><strong>Approved</strong><span>10 May · 12:15 PM</span></div></div><div class="step"><i>✓</i><div><strong>Dispatched</strong><span>11 May · 09:40 AM</span></div></div><div class="step"><i>4</i><div><strong>Shifted to Inventory</strong><span>अगला अपडेट</span></div></div></div></article>';
if(operational==='dispatch')return '<article class="feature-card card"><h3>कंपनी डिस्पैच</h3><p>Finalized quantity: <b>1,250 kg</b> · Vehicle ready</p><div class="inline-grid"><div class="info"><small>Logistics partner</small><b>Green Line</b></div><div class="info"><small>Driver</small><b>राकेश कुमार</b></div><div class="info"><small>फोन</small><b>98765 43210</b></div><div class="info"><small>Vehicle</small><b>UP32 CT 5678</b></div></div><button class="primary" onclick="showToast(\'Driver को dispatch confirmation भेज दिया गया\')">डिस्पैच कन्फर्म करें</button></article>';
return '<article class="feature-card card"><h3>नया बैच बनाएं</h3><p>कलेक्शन होने के बाद batch ID अपने-आप बनेगी।</p><div class="inline-grid"><div class="info"><small>किसान</small><b>रानी कुमारी</b></div><div class="info"><small>Crop / Grade</small><b>सरसों / A</b></div><div class="info"><small>वजन</small><b>9 क्विंटल</b></div><div class="info"><small>Proof photo</small><b>तैयार</b></div></div><button class="primary" onclick="showToast(\'Batch ID KJE-2605-014 बन गया\')">Batch ID बनाएं</button></article>'}
function more(){return '<div class="screen-head"><div><h1>और</h1><p>प्रोफाइल, earning और सहायता</p></div></div><button class="row-action" onclick="profile()"><div class="shortcut-icon">♙</div><div><strong>मेरा प्रोफाइल</strong><span>नाम, उम्र, फोन, Aadhaar, employee ID और salary</span></div><b class="arrow">›</b></button><button class="row-action" onclick="earnings()"><div class="shortcut-icon" style="background:#fff6dd;color:#a06c00">₹</div><div><strong>कमाई और रेफरल</strong><span>Salary + referral earnings + bonuses + incentives</span></div><b class="arrow">›</b></button><button class="row-action" onclick="performance()"><div class="shortcut-icon" style="background:#fff0ea;color:#c8653b">★</div><div><strong>Performance dashboard</strong><span>Task completion, quantity, delivery और AI rating</span></div><b class="arrow">›</b></button><button class="row-action" onclick="showToast(\'Offline mode: visits, weights और photos सुरक्षित रहेंगे\')"><div class="shortcut-icon">↻</div><div><strong>ऑफलाइन मोड</strong><span>नेटवर्क के बिना record करें, बाद में sync करें</span></div><b class="arrow">›</b></button><button class="row-action" onclick="showToast(\'कंपनी हेल्पलाइन: 1800 123 4567\')"><div class="shortcut-icon" style="background:#ebf2f7;color:#2f75a5">?</div><div><strong>मदद और सहायता</strong><span>One-tap company support और helpline</span></div><b class="arrow">›</b></button><button class="row-action" onclick="showToast(\'Secure logout demo complete\')"><div class="shortcut-icon" style="background:#fff0ea;color:#c8653b">↪</div><div><strong>सुरक्षित लॉगआउट</strong><span>Demo preview में कोई data remove नहीं हुआ</span></div><b class="arrow">›</b></button>'}
function profile(){showToast('अमित कुमार · AGT1256 · ₹20,000 salary · ₹5,680 bonus')}
function earnings(){showToast('इस महीने ₹45,680 · रेफरल किसान 22 · रेफरल कमाई ₹6,250')}
function performance(){showToast('AI rating 4.6/5 · 48/52 tasks · review threshold: 2.0 से कम')}
function render(){var view=current==='home'?home():current==='tasks'?tasks():current==='farmers'?farmersView():current==='operations'?operations():more();document.getElementById('app').innerHTML=view;renderNav()}
function go(v){current=v;render();window.scrollTo(0,0)}
function setOperation(v){operational=v;current='operations';render()}
function completeTask(button,index){if(index===0&&openTasks>0){openTasks--;button.textContent='पूरा हुआ';button.style.background='#2f8057';showToast('कलेक्शन सुरक्षित हुआ · Batch creation के लिए तैयार');renderNav()}else{showToast('Task detail खुल गया') }}
function listen(){var title=document.getElementById('voiceTitle');if(title){title.textContent='सुन रहा हूं… “आज के टास्क दिखाओ”';setTimeout(function(){title.textContent='आपके 4 priority tasks तैयार हैं';showToast('Voice command समझ लिया गया')},1100)}}
function filterFarmers(query){var q=query.toLowerCase();var list=farmers.filter(function(f){return f.join(' ').toLowerCase().indexOf(q)>-1});document.getElementById('farmerList').innerHTML=farmerRows(list)}
function openLanguage(){document.getElementById('sheet').classList.add('show')}
function setLanguage(name){language=name;document.querySelector('.language').textContent=name;document.getElementById('sheet').classList.remove('show');showToast(name+' भाषा चुनी गई')}
function showToast(text){var t=document.getElementById('toast');t.textContent=text;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(function(){t.classList.remove('show')},2800)}
document.getElementById('sheet').addEventListener('click',function(e){if(e.target===this)this.classList.remove('show')});render();
